from random import choice
from sys import argv
NUMBERS = ('0','1','2','3','4','5','6','7','8','9')

def format_surname(surname:str) -> str:
    '''Takes a string 'surname' as input and returns the formatted version of the surname by removing any character other than alphabets.'''
    formatted_surname = ''
    for character in surname:
        # Ignoring any other characters than alphabets
        if ord('a')<=ord(character)<=ord('z'):
            formatted_surname += character
    return formatted_surname

def email_generator(forename: str, surname: str) -> str:
    '''Takes two strings 'forename' and 'surname' as input and returns a string that represents an email address. The email address is generated by taking the first letter of each word in the forename and concatenating it with the surname, followed by a random four-digit number and the domain name "@poppleton.ac.uk'''
    email = ''
    initials = forename.split()
    # Add the first letter from initials to 'email'
    for j in initials:
        email += j[0]+"."
    email += surname
    # Randomly four numbers are selected and concatenate to 'email' string
    for j in range(4):
        email += choice(NUMBERS)
    return email + "@poppleton.ac.uk"

# This program generates emails and stores in new file
if __name__ == "__main__":
    try:
        file_name = argv[1]
        with open(file_name) as fp:
            id = [data.split()[0] for data in fp]
            # Changes the position of file to 0th position.
            fp.seek(0)
            forenames = [data.split(", ")[1].strip("\n").lower() for data in fp]
            fp.seek(0)
            surnames = []
            for data in fp:
                surname = data[9:].split(",")[0]
                formatted_surname = format_surname(surname.lower())
                surnames.append(formatted_surname.lower())

        emails = []
        # Email is generated by calling email_generator function and appended in emails list
        for i in range (0,len(id)):
            email = email_generator(forenames[i], surnames[i])
            emails.append(email)
            
        # If user has provided name for new file, the name will be used or else 'emails' will be used
        new_file_name = argv[2] if len(argv) == 3 else 'emails.txt'
        with open(new_file_name, 'w') as f_new:
            for i in range(0,len(id)):
                f_new.write(f'{id[i]} {emails[i]}\n')

    except IndexError:
        print("Error: Missing command-line argument.")
    except FileNotFoundError:
        print(f'Error: Cannot open "{file_name}". Sorry about that.')
        